### PR TITLE
Added all the colors for my project

### PR DESCRIPTION
**Pull request by ScoobyDubeyDo**
Hey Guys, I have chosen all the colors which I am going to use for this project, please give your reviews.

### CODE REVIEW

**Review by manismk — APPROVED** [review]
Everything looks good!

**Review by muskaanshah — APPROVED** [review]
Sahi hai

**Review by xsaurabhsuthar — APPROVED** [review]
You can add green and blue also as they're primary colors in branding.

**Comment by ScoobyDubeyDo** [comment]
Don't want to merge it now.

**Pull request closed without merging**
